 const enCOUNTRIES = [
    {id: 0,name:'All'},
    {id: 1,name:'Afghanistan'},
    {id: 2,name:'Albania'},
    {id: 3,name:'Algeria'},
    {id: 4,name:'Andorra'},
    {id: 5,name:'Angola'},
    {id: 6,name:'Antigua and Barbuda'},
    {id: 7,name:'Argentina'},
    {id: 8,name:'Armenia'},
    {id: 9,name:'Australia'},
    {id: 10,name:'Austria'},
    {id: 11,name:'Austrian Empire'},
    {id: 12,name:'Azerbaijan'},
    {id: 13,name:'Baden*'},
    {id: 14,name:'Bahamas, The'},
    {id: 15,name:'Bahrain'},
    {id: 16,name:'Bangladesh'},
    {id: 17,name:'Barbados'},
    {id: 18,name:'Bavaria*'},
    {id: 19,name:'Belarus'},
    {id: 20,name:'Belgium'},
    {id: 21,name:'Belize'},
    {id: 22,name:'Benin (Dahomey)'},
    {id: 23,name:'Bolivia'},
    {id: 24,name:'Bosnia and Herzegovina'},
    {id: 25,name:'Botswana'},
    {id: 26,name:'Brazil'},
    {id: 27,name:'Brunei'},
    {id: 28,name:'Brunswick and Lüneburg'},
    {id: 29,name:'Bulgaria'},
    {id: 30,name:'Burkina Faso (Upper Volta)'},
    {id: 31,name:'Burma'},
    {id: 32,name:'Burundi'},
    {id: 33,name:'Cabo Verde'},
    {id: 34,name:'Cambodia'},
    {id: 35,name:'Cameroon'},
    {id: 36,name:'Canada'},
    {id: 37,name:'Cayman Islands, The Central African Republic'},
    {id: 38,name:'Central American Federation*'},
    {id: 39,name:'Chad'},
    {id: 40,name:'Chile'},
    {id: 41,name:'China'},
    {id: 42,name:'Colombia'},
    {id: 43,name:'Comoros'},
    {id: 44,name:'Congo Free State, The'},
    {id: 45,name:'Costa Rica'},
    {id: 46,name:'Cote d’Ivoire (Ivory Coast)'},
    {id: 47,name:'Croatia'},
    {id: 48,name:'Cuba'},
    {id: 49,name:'Cyprus'},
    {id: 50,name:'Czechia'},
    {id: 51,name:'Czechoslovakia'},
];
const koCOUNTRIES = [
    {id: 0,name:'모두'},
    { id: 1, name:'Afghanistan'},
    { id: 2, name:'Albania'},
    { id: 3, name:'Algeria'},
    {id: 4,name:'Andorra'},
    {id: 5,name:'Angola'},
    {id: 6,name:'Antigua and Barbuda'},
    {id: 7,name:'Argentina'},
    {id: 8,name:'Armenia'},
    {id: 9,name:'Australia'},
    {id: 10,name:'Austria'},
    {id: 11,name:'Austrian Empire'},
    {id: 12,name:'Azerbaijan'},
    {id: 13,name:'Baden*'},
    {id: 14,name:'Bahamas, The'},
    {id: 15,name:'Bahrain'},
    {id: 16,name:'Bangladesh'},
    {id: 17,name:'Barbados'},
    {id: 18,name:'Bavaria*'},
    {id: 19,name:'Belarus'},
    {id: 20,name:'Belgium'},
    {id: 21,name:'Belize'},
    {id: 22,name:'Benin (Dahomey)'},
    {id: 23,name:'Bolivia'},
    {id: 24,name:'Bosnia and Herzegovina'},
    {id: 25,name:'Botswana'},
    {id: 26,name:'Brazil'},
    {id: 27,name:'Brunei'},
    {id: 28,name:'Brunswick and Lüneburg'},
    {id: 29,name:'Bulgaria'},
    {id: 30,name:'Burkina Faso (Upper Volta)'},
    {id: 31,name:'Burma'},
    {id: 32,name:'Burundi'},
    {id: 33,name:'Cabo Verde'},
    {id: 34,name:'Cambodia'},
    {id: 35,name:'Cameroon'},
    {id: 36,name:'Canada'},
    {id: 37,name:'Cayman Islands, The Central African Republic'},
    {id: 38,name:'Central American Federation*'},
    {id: 39,name:'Chad'},
    {id: 40,name:'Chile'},
    {id: 41,name:'China'},
    {id: 42,name:'Colombia'},
    {id: 43,name:'Comoros'},
    {id: 44,name:'Congo Free State, The'},
    {id: 45,name:'Costa Rica'},
    {id: 46,name:'Cote d’Ivoire (Ivory Coast)'},
    {id: 47,name:'Croatia'},
    {id: 48,name:'Cuba'},
    {id: 49,name:'Cyprus'},
    {id: 50,name:'Czechia'},
    {id: 51,name:'Czechoslovakia'},
];
module.exports = {enCOUNTRIES, koCOUNTRIES}